---
couchbase-server:
  '5.5':
    release:  '5.5.6'
    stable:   '5.5.6'
  '6.0':
    release:  '6.0.5'
    stable:   '6.0.5-3340'
  '6.5':
    release:  '6.5.2'
    stable:   '6.5.2-6625'
  '6.6':
    release:  '6.6.1'
    stable:   '6.6.2-9556'
  '7.0':
    stable:   '7.0.0-4797'

# Other_products:
couchbase-operator:
  '1.2':
    release:  '1.2.2'
    stable:   '1.2.2'
  '2.0':
    release:  '2.0.1'
    stable:   '2.0.1'
# sync_gateway: etc
...
