Couchbase-server:
  5.5:
    Released:  "5.5.6"
    Stable:    "5.5.6"
  6.0:
    Released:  "6.0.4"
    Stable:    "6.0.4"
  6.5:
    Released:  "6.5.1"
    Stable:    "6.5.1"
  6.6:
    Released:  "NA"
    Stable:    "6.6.0-7813"
  7.0:
    Released:  "NA"
    Stable:    "7.0.0-2416"

# Other_products:
# Couchbase_Mobile:
# Sync_Gateway:
