---
couchbase-server:
  '5.5':
    release:  '5.5.6'
    stable:   '5.5.6'
  '6.0':
    release:  '6.0.4'
    stable:   '6.0.4'
  '6.5':
    release:  '6.5.1'
    stable:   '6.5.1'
  '6.6':
    release:  '6.6.0'
    stable:   '6.6.0-7920'
  '7.0':
    stable:   '7.0.0-3342'

# Other_products:
couchbase-operator:
  '1.2':
    release:  '1.2.2'
    stable:   '1.2.2'
  '2.0':
    release:  '2.0.1'
    stable:   '2.0.1'
# sync_gateway: etc
...
